[build]
  command = "npm install && npm run build"
  publish = "build"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 

[context.production.environment]
  REACT_APP_BACKEND_URL = "/"