services:
  - type: web
    name: image-search-app
    env: node
    buildCommand: chmod +x build.sh && ./build.sh
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 20.11.1 