services:
  - type: web
    name: image-search-app
    env: node
    buildCommand: |
      npm install --legacy-peer-deps
      npm install react-scripts --save
      npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 20.11.1 